name: CI

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install -g npm@latest
          npm install @rollup/rollup-linux-x64-gnu --save-optional
          npm install --no-optional
          npm install
      - name: Auto-fix lint issues
        run: npx eslint . --fix
      - name: Run lint
        run: npm run lint -- --max-warnings=0
      - name: Run tests
        run: npm run test
      - name: Solve vulnerabilities
        run: npm audit fix --force || true
      - name: Run security audit (moderate)
        run: npm audit --audit-level=moderate
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: tests/
