name: Deploy to Vercel (CI → CD)

on:
  # Manual run (useful for first deploy or hotfixes)
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or ref to deploy (default: main)'
        required: false
        default: 'main'

  # Trigger only when CI workflow completes successfully
  workflow_run:
    workflows: ["CI"]        # <-- must exactly match "name:" in ci.yml
    types:
      - completed
      
jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    concurrency:
      group: vercel-deploy
      cancel-in-progress: true
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'workflow_run' &&
       github.event.workflow_run.conclusion == 'success' &&
       github.event.workflow_run.head_branch == 'main')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.ref || github.event.workflow_run.head_branch }}

      - name: Print current branch (debug)
        run: git branch --show-current

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi

      - name: Build (Vite)
        run: npm run build

      - name: Ensure build output exists
        run: |
          if [ ! -d dist ]; then echo "Build failed: dist/ not found"; exit 1; fi

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          zeit-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_TEAM_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./