name: Deploy to Vercel (CI → CD)

on:
  # Manual run (useful for first deploy from cd branch)
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or ref to deploy (default: main)'
        required: false
        default: 'main'

  # Trigger when the CI workflow completes successfully
  workflow_run:
    workflows: ["CI"]        # <-- must match the "name:" of your CI workflow
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.ref || github.ref }}

      - name: Setup Node.js (cache npm)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install -g npm@latest
          npm install @rollup/rollup-linux-x64-gnu --save-optional
          npm install --no-optional
          npm install

      - name: Build (Vite)
        env:
          CI: false  # This prevents treating warnings as errors
        run: npm run build

      - name: Ensure build output exists
        run: |
          if [ ! -d dist ]; then 
            echo "Build failed: dist/ not found"
            echo "Build output:"
            ls -la
            exit 1
          fi
          echo "Build output contents:"
          ls -la dist/

      - name: Validate Vercel Configuration
        run: |
          if [ -z "${{ secrets.VERCEL_TOKEN }}" ]; then
            echo "Error: VERCEL_TOKEN is not set in repository secrets"
            exit 1
          fi
          if [ -z "${{ secrets.VERCEL_TEAM_ID }}" ]; then
            echo "Error: VERCEL_TEAM_ID is not set in repository secrets"
            exit 1
          fi
          if [ -z "${{ secrets.VERCEL_PROJECT_ID }}" ]; then
            echo "Error: VERCEL_PROJECT_ID is not set in repository secrets"
            exit 1
          fi

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_TEAM_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
          prod: ${{ github.ref == 'refs/heads/main' || (github.event_name == 'workflow_dispatch' && github.event.inputs.ref == 'main') || (github.event_name == 'workflow_run' && github.event.workflow_run.head_branch == 'main') }}
